### ISSUE TITLE
Ai did not speaking

### ISSUE THREAD

**Issue by Kevinsathvik182** [Amitminer/Jarvis-Termux#1]

**Comment by Amitminer** [comment]
---
To fix microphone issue, you'll need to install the Termux-API app from F-Droid. You can find it [here](https://f-droid.org/en/packages/com.termux.api/).

After you've got Termux-API installed, open Termux and run the following command:

```
pkg install termux-api
```

Once that's done, you should be able to use Termux-API features, like [termux-tts-speak](https://wiki.termux.com/wiki/Termux-tts-speak). You might see a popup asking for permissions, such as access to the microphone—go ahead and grant those as needed.
i hope this helps fix the issue..

**Comment by Kevinsathvik182** [comment]
It installed but termux-tts-speak command not working it asks for
permission while entering the command it shows permission dined

**Comment by Amitminer** [comment]
console log please?

**Comment by Amitminer** [comment]
Run this command  ``termux-microphone-record` -l 3`` in termux console/shell..
it will ask permission to grant/deny microphone acesss..
